name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:

    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Code lint
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: lint

    - name: Unit tests
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test

    - name: Build project
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: Install gitbook dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: docs:install

    - name: Build docs
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: docs:build
